"""Fix bars where the adjustment was lost (adj_* == raw_*, factor 1.0) — caused by
fill_adj_gap.py blindly filling NaN-adj bars with raw. The split/div factor is constant
within a trading day, so we recompute the corrupted bars from that day's REAL factor
(median over the day's non-unity bars) and rescale adj price + adj volume accordingly.

Detection: a bar's price factor (adj_close/raw_close) deviating >5% from its day's true
factor is corrupted. Days that are genuinely ~1.0 throughout (recent back-adjust anchor)
have no non-unity bars -> left untouched.

Writes BASE 13 columns only (drops stale indicators); rerun compute_indicators.py after,
then round_compact.py. Operates on by_symbol/ (30-min); features_daily is regenerated by
the recompute.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import numpy as np
import pandas as pd

BASE = [
    "ts",
    "et_time",
    "symbol",
    "raw_open",
    "raw_high",
    "raw_low",
    "raw_close",
    "raw_volume",
    "adj_open",
    "adj_high",
    "adj_low",
    "adj_close",
    "adj_volume",
]
PRICE_PAIRS = [
    ("adj_open", "raw_open"),
    ("adj_high", "raw_high"),
    ("adj_low", "raw_low"),
    ("adj_close", "raw_close"),
]
UNITY_TOL = 0.005  # treat |factor-1|<=0.5% as "looks unadjusted"
DEV_TOL = 0.05  # >5% off the day's true factor = corrupted


def _fix(path_str: str):
    path = Path(path_str)
    df = pd.read_parquet(path).sort_values("ts").reset_index(drop=True)
    # upcast the float32 columns we mutate (can't assign float64 into a float32 column)
    for c in (
        "raw_open",
        "raw_high",
        "raw_low",
        "raw_close",
        "adj_open",
        "adj_high",
        "adj_low",
        "adj_close",
    ):
        if c in df.columns:
            df[c] = df[c].astype("float64")

    rawc = df["raw_close"]
    fac = df["adj_close"] / rawc.where(rawc != 0)
    rawv = df["raw_volume"].astype("float64")
    vfac = df["adj_volume"].astype("float64") / rawv.where(rawv != 0)
    day = df["et_time"].dt.normalize()

    # day's true factor = median over bars that are NOT near-unity; fallback = day median
    nonunity = fac.where((fac - 1.0).abs() > UNITY_TOL)
    dpf = nonunity.groupby(day).transform("median")
    dpf = dpf.fillna(fac.groupby(day).transform("median"))
    nonunity_v = vfac.where((fac - 1.0).abs() > UNITY_TOL)  # use price-factor mask for volume too
    dvf = nonunity_v.groupby(day).transform("median")
    dvf = dvf.fillna(vfac.groupby(day).transform("median"))

    bad = ((fac - dpf).abs() / dpf > DEV_TOL).fillna(False).to_numpy()
    n = int(bad.sum())
    if n == 0:
        return (0, 0)

    for a, r in PRICE_PAIRS:
        df.loc[bad, a] = (df[r] * dpf).to_numpy()[bad]
    newvol = (df["raw_volume"].astype("float64") * dvf).round()
    adjvol = df["adj_volume"].astype("float64").to_numpy().copy()
    adjvol[bad] = newvol.to_numpy()[bad]
    df["adj_volume"] = np.round(adjvol).astype("int64")

    out = df[[c for c in BASE if c in df.columns]]
    tmp = path.with_suffix(".parquet.tmp")
    out.to_parquet(tmp, engine="pyarrow", compression="zstd", index=False)
    os.replace(tmp, path)
    return (1, n)


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--by-symbol-root", default=r"D:\BaiduNetdiskDownload\30min\30min_data")
    p.add_argument("--scope", choices=["all", "stock", "etf"], default="all")
    p.add_argument("--workers", type=int, default=min(16, os.cpu_count() or 1))
    p.add_argument("--symbols", nargs="*")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    ats = ["stock", "etf"] if args.scope == "all" else [args.scope]
    files = [
        str(f) for at in ats for f in sorted((Path(args.by_symbol_root) / at).glob("*.parquet"))
    ]
    if args.symbols:
        only = {s.upper() for s in args.symbols}
        files = [f for f in files if Path(f).stem.upper() in only]
    print(f"scanning {len(files):,} files, workers={args.workers}")
    started = time.time()
    fixed_files = fixed_bars = errs = 0
    with ProcessPoolExecutor(max_workers=args.workers) as ex:
        futs = [ex.submit(_fix, f) for f in files]
        for done, fut in enumerate(as_completed(futs), 1):
            try:
                ff, nb = fut.result()
                fixed_files += ff
                fixed_bars += nb
            except Exception as exc:  # noqa: BLE001
                errs += 1
                print("  ERR", repr(exc), file=sys.stderr)
            if done % 1000 == 0:
                print(
                    f"  {done:,}/{len(files):,} fixed_files={fixed_files:,} fixed_bars={fixed_bars:,} "
                    f"{time.time() - started:,.0f}s",
                    file=sys.stderr,
                    flush=True,
                )
    print(
        f"done: files_with_fix={fixed_files:,} bars_fixed={fixed_bars:,} errors={errs} "
        f"elapsed={time.time() - started:,.0f}s"
    )
    print("NEXT: compute_indicators.py --scope all  ->  round_compact.py --scope all")
    return 0 if errs == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
